-- ROLLBACK for live-create-erpts-tables.sql: drops ONLY the 42 ErpTS* tables it created.
-- Destroys any data in them. Never touches ERP-owned tables.
SET XACT_ABORT ON; BEGIN TRAN;
ALTER TABLE [dbo].[ErpTSProjectQsAssignment] DROP CONSTRAINT [ErpTSProjectQsAssignment_projectId_fkey];
ALTER TABLE [dbo].[ErpTSProjectQsStatus] DROP CONSTRAINT [ErpTSProjectQsStatus_projectId_fkey];
ALTER TABLE [dbo].[ErpTSTask] DROP CONSTRAINT [ErpTSTask_projectId_fkey];
ALTER TABLE [dbo].[ErpTSRetailTaskDetail] DROP CONSTRAINT [ErpTSRetailTaskDetail_taskId_fkey];
ALTER TABLE [dbo].[ErpTSProjectTaskDetail] DROP CONSTRAINT [ErpTSProjectTaskDetail_taskId_fkey];
ALTER TABLE [dbo].[ErpTSProjectSignRow] DROP CONSTRAINT [ErpTSProjectSignRow_projectId_fkey];
ALTER TABLE [dbo].[ErpTSProjectAttachment] DROP CONSTRAINT [ErpTSProjectAttachment_projectId_fkey];
ALTER TABLE [dbo].[ErpTSRetailTaskDetailAttachment] DROP CONSTRAINT [ErpTSRetailTaskDetailAttachment_retailTaskDetailId_fkey];
ALTER TABLE [dbo].[ErpTSProjectTaskDetailAttachment] DROP CONSTRAINT [ErpTSProjectTaskDetailAttachment_projectTaskDetailId_fkey];
ALTER TABLE [dbo].[ErpTSSignageDetail] DROP CONSTRAINT [ErpTSSignageDetail_taskId_fkey];
ALTER TABLE [dbo].[ErpTSChatterPost] DROP CONSTRAINT [ErpTSChatterPost_taskId_fkey];
ALTER TABLE [dbo].[ErpTSChatterPost] DROP CONSTRAINT [ErpTSChatterPost_projectId_fkey];
ALTER TABLE [dbo].[ErpTSChatterComment] DROP CONSTRAINT [ErpTSChatterComment_postId_fkey];
ALTER TABLE [dbo].[ErpTSChatterPostMention] DROP CONSTRAINT [ErpTSChatterPostMention_postId_fkey];
ALTER TABLE [dbo].[ErpTSChatterCommentMention] DROP CONSTRAINT [ErpTSChatterCommentMention_commentId_fkey];
ALTER TABLE [dbo].[ErpTSChatterPostLike] DROP CONSTRAINT [ErpTSChatterPostLike_postId_fkey];
ALTER TABLE [dbo].[ErpTSChatterPostSeen] DROP CONSTRAINT [ErpTSChatterPostSeen_postId_fkey];
ALTER TABLE [dbo].[ErpTSChatterPostAttachment] DROP CONSTRAINT [ErpTSChatterPostAttachment_chatterPostId_fkey];
ALTER TABLE [dbo].[ErpTSLinkAttachment] DROP CONSTRAINT [ErpTSLinkAttachment_chatterPostId_fkey];
ALTER TABLE [dbo].[ErpTSRegularizationRequest] DROP CONSTRAINT [ErpTSRegularizationRequest_taskId_fkey];
ALTER TABLE [dbo].[ErpTSReallocationRequest] DROP CONSTRAINT [ErpTSReallocationRequest_taskId_fkey];
ALTER TABLE [dbo].[ErpTSOvertimeRequest] DROP CONSTRAINT [ErpTSOvertimeRequest_taskId_fkey];
ALTER TABLE [dbo].[ErpTSOvertimeApprovalHistory] DROP CONSTRAINT [ErpTSOvertimeApprovalHistory_requestId_fkey];
ALTER TABLE [dbo].[ErpTSOvertimeAttachment] DROP CONSTRAINT [ErpTSOvertimeAttachment_overtimeRequestId_fkey];
ALTER TABLE [dbo].[ErpTSSchedulerAssignment] DROP CONSTRAINT [ErpTSSchedulerAssignment_taskId_fkey];
ALTER TABLE [dbo].[ErpTSSchedulerTaskFragment] DROP CONSTRAINT [ErpTSSchedulerTaskFragment_taskId_fkey];
ALTER TABLE [dbo].[ErpTSActivityLog] DROP CONSTRAINT [ErpTSActivityLog_taskId_fkey];
ALTER TABLE [dbo].[ErpTSConversationParticipant] DROP CONSTRAINT [ErpTSConversationParticipant_conversationId_fkey];
ALTER TABLE [dbo].[ErpTSMessage] DROP CONSTRAINT [ErpTSMessage_conversationId_fkey];
ALTER TABLE [dbo].[ErpTSTaskWorkSession] DROP CONSTRAINT [ErpTSTaskWorkSession_taskId_fkey];
ALTER TABLE [dbo].[ErpTSTaskWorkSessionFile] DROP CONSTRAINT [ErpTSTaskWorkSessionFile_sessionId_fkey];
ALTER TABLE [dbo].[ErpTSTaskDesigner] DROP CONSTRAINT [ErpTSTaskDesigner_taskId_fkey];
DROP TABLE IF EXISTS [dbo].[ErpTSProject];
DROP TABLE IF EXISTS [dbo].[ErpTSProjectQsAssignment];
DROP TABLE IF EXISTS [dbo].[ErpTSProjectQsStatus];
DROP TABLE IF EXISTS [dbo].[ErpTSTask];
DROP TABLE IF EXISTS [dbo].[ErpTSRetailTaskDetail];
DROP TABLE IF EXISTS [dbo].[ErpTSProjectTaskDetail];
DROP TABLE IF EXISTS [dbo].[ErpTSProjectSignRow];
DROP TABLE IF EXISTS [dbo].[ErpTSProjectAttachment];
DROP TABLE IF EXISTS [dbo].[ErpTSRetailTaskDetailAttachment];
DROP TABLE IF EXISTS [dbo].[ErpTSProjectTaskDetailAttachment];
DROP TABLE IF EXISTS [dbo].[ErpTSDesignTask];
DROP TABLE IF EXISTS [dbo].[ErpTSSignageDetail];
DROP TABLE IF EXISTS [dbo].[ErpTSChatterPost];
DROP TABLE IF EXISTS [dbo].[ErpTSChatterComment];
DROP TABLE IF EXISTS [dbo].[ErpTSChatterPostMention];
DROP TABLE IF EXISTS [dbo].[ErpTSChatterCommentMention];
DROP TABLE IF EXISTS [dbo].[ErpTSChatterPostLike];
DROP TABLE IF EXISTS [dbo].[ErpTSChatterPostSeen];
DROP TABLE IF EXISTS [dbo].[ErpTSChatterPostAttachment];
DROP TABLE IF EXISTS [dbo].[ErpTSLinkAttachment];
DROP TABLE IF EXISTS [dbo].[ErpTSLeaveRequest];
DROP TABLE IF EXISTS [dbo].[ErpTSRegularizationRequest];
DROP TABLE IF EXISTS [dbo].[ErpTSReallocationRequest];
DROP TABLE IF EXISTS [dbo].[ErpTSOvertimeRequest];
DROP TABLE IF EXISTS [dbo].[ErpTSOvertimeApprovalHistory];
DROP TABLE IF EXISTS [dbo].[ErpTSOvertimeAttachment];
DROP TABLE IF EXISTS [dbo].[ErpTSSchedulerAssignment];
DROP TABLE IF EXISTS [dbo].[ErpTSSchedulerTaskFragment];
DROP TABLE IF EXISTS [dbo].[ErpTSSchedulerWeek];
DROP TABLE IF EXISTS [dbo].[ErpTSSchedulerAssignmentHistory];
DROP TABLE IF EXISTS [dbo].[ErpTSHoliday];
DROP TABLE IF EXISTS [dbo].[ErpTSSchedulerDayUnlock];
DROP TABLE IF EXISTS [dbo].[ErpTSLeaveRescheduleSnapshot];
DROP TABLE IF EXISTS [dbo].[ErpTSActivityLog];
DROP TABLE IF EXISTS [dbo].[ErpTSNotification];
DROP TABLE IF EXISTS [dbo].[ErpTSInboxRead];
DROP TABLE IF EXISTS [dbo].[ErpTSConversation];
DROP TABLE IF EXISTS [dbo].[ErpTSConversationParticipant];
DROP TABLE IF EXISTS [dbo].[ErpTSMessage];
DROP TABLE IF EXISTS [dbo].[ErpTSTaskWorkSession];
DROP TABLE IF EXISTS [dbo].[ErpTSTaskWorkSessionFile];
DROP TABLE IF EXISTS [dbo].[ErpTSTaskDesigner];
COMMIT TRAN;
